version: "3.7"

services:
    appProxy:
        container_name: nginx
        image: nginx:latest
        ports:
          - 80:80
          - 443:443
        volumes:
          - /var/lib/nginx/php:/var/www/myapp
          - /var/lib/nginx/site.conf:/etc/nginx/conf.d/site.conf